version: '3'
services:
  # db:
  #   image: postgres
  #   volumes:
  #     - /var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app:rw
    ports:
      - "3000:3000"
    networks:
      - dockernet    
    # depends_on:
    #   - db
    
networks:
  dockernet:
    external: true
  